options:
   logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/myfirstapp-72240/assignment-02-backend:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/myfirstapp-72240/assignment-02-backend:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'deployment.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/assignment-02-backend-deployment'
      - 'assignment-02-backend=gcr.io/myfirstapp-72240/assignment-02-backend:$SHORT_SHA'
      - '--namespace=assignment-02-backend'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
images:
  - 'gcr.io/myfirstapp-72240/assignment-02-backend:$SHORT_SHA'
substitutions:
  _ZONE: 'us-central1-a'
  _CLUSTER_NAME: 'assignment-02-cluster'

