apiVersion: v1
kind: Namespace
metadata:
  name: assignment-02-backend

---

apiVersion: v1
kind: Secret
metadata:
  name: assignment-02-backend-secrets
  namespace: assignment-02-backend
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: assignment-02-backend-configmap
  namespace: assignment-02-backend
data:
  DB_HOST: "34.130.38.87"
  DB_NAME: "myappdb"
  DB_USER: "myuser"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: assignment-02-backend-deployment
  namespace: assignment-02-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: assignment-02-backend-app
  template:
    metadata:
      labels:
        app: assignment-02-backend-app
    spec:
      containers:
        - name: assignment-02-backend
          image: gcr.io/myfirstapp-72240/assignment-02-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: assignment-02-backend-configmap
            - secretRef:
                name: assignment-02-backend-secrets
      imagePullSecrets:
        - name: gcr-json-key

---

apiVersion: v1
kind: Service
metadata:
  name: assignment-02-backend-service
  namespace: assignment-02-backend
spec:
  type: ClusterIP
  selector:
    app: assignment-02-backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

