apiVersion: v1
kind: Namespace
metadata:
  name: backend

---

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: backend
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bucket-info
  namespace: backend
data:
    BUCKET_NAME: "cbd-3354-bucket"
    DB_HOST: "104.155.137.239"
    DB_NAME: "myappdb"
    DB_USER: "myuser"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
        version: v1
    spec:
      containers:
        - name: backend-app
          image: us-central1-docker.pkg.dev/myfirstapp-72240/cbd-3354-ica4-repository/app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: bucket-info

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: backend-app
