apiVersion: v1
kind: Namespace
metadata:
  name: backend

---

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: backend
type: Opaque
data:
  DB_PASSWORD: c2VjcmV0LW5hbWU=


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: bucket-info
  namespace: backend
data:
    BUCKET_NAME: "my-bucket-name"
    DB_HOST: "c2VjcmV0LW5hbWU="
    DB_NAME: "c2VjcmV0LW5hbWU="
    DB_USER: "c2VjcmV0LW5hbWU="
    GOOGLE_APPLICATION_CREDENTIALS: "bucket_access_key.json"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
        version: v1
    spec:
      containers:
        - name: backend-app
          image: gcr.io/myfirstapp-72240/backend-app:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: bucket-info

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: backend-app
