apiVersion: v1
kind: Namespace
metadata:
  name: backend

---


apiVersion: v1
kind: Secret
metadata:
  name: gcr-json-key
  namespace: backend
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICJnY3IuaW8iOiB7DQogICAgICAgICJ1c2VybmFtZSI6ICJfanNvbl9rZXkiLA0KICAgICAgICAicGFzc3dvcmQiOiB7DQogICAgICAgICAgICAidHlwZSI6ICJzZXJ2aWNlX2FjY291bnQiLA0KICAgICAgICAgICAgInByb2plY3RfaWQiOiAibXlmaXJzdGFwcC03MjI0MCIsDQogICAgICAgICAgICAicHJpdmF0ZV9rZXlfaWQiOiAiMzNjNTEzZTFlNjFiMGE5MWNmNmFiZGJjNTI3MDVlNDU5YTdlODk2NyIsDQogICAgICAgICAgICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dnZ1NqQWdFQUFvSUJBUUN1RW1CRmNFOEMwWWllXG54eDArajZNdVdBaUpReFYxdTVCSFFDL1Z5aEc2Q291dkNUYzJaaU9RcXBzRXRySk5kaEpXU1RjclJFOE5kN09rXG50cFJDR01YRENzZHBrNDQrUXphTHE4eU1VZ05xM2FjVFdlMjA5QVIzTVY5Q0tDdjJCa3Y3U1Nhb3pIemxZZXcyXG44eWg5Yk9GUXNIWWhQTFNoeGt0SUQ0cTU3S0JENXBNd2htNjdLUVM4anMwSTBuTzlzZ3dPTm5CY0xZUXUrQ2Y2XG5TYmZjd0EwM2xoQmVmRmtxUEhjdXkrYjlnMGxmbEVjdFdaVUJrdjhuaVcraXZveS9QRXRBLzF2RFR0cHR4R0FNXG5wV04wSWxSdjRmRlRqbjdpWmoxSDdYOGcyTi9hSEhZVHhMNUE4VVNsbWtnUWhXOHdmTnBoV0NPdHdlZ2hpZTVPXG5FYmpBMDNHeEFnTUJBQUVDZ2dFQUFnNG1zSEdab0d4SzdOMEJZLzJDazRlMGtIOGhyTHY5bXh6MTV0UWNLRVdVXG56ZFdyYTlHYnRrcjIvVFBiMDMwY3pSMDJNUEg5VkNqSGRUaWREWVVpandmOGpNVEZjUHNvTGxETCtVZ3FuY05uXG5CRFd0QTI0bFdjQ0hTR2V2MGY0SENuQlBSWXRaV2lzeE44MnRMaHhXWllOTXExM0xocGZjKzBsdTVCYXh3Q0hlXG55dXdSRGJOb1Q0N2hhdTY4ZFRCak5SOFRQRHFOc2tHdUpyUnNvNW5uWjd5Z20zWjFXY3d5aFMvQ3hlNmdSQmdVXG5EakxDSyszTGI5T1RmaU5JMnYwRUZQbUJYYVUyZXZ2MHpGN1RTS1JDZ2UzN2FnaTVDZ2dHVFpmZ0FyMXUrQjFnXG5XNDlzaWN4a2hxYlVlVE5zZy8yS2lzdkZrenp5TEw5R21aa3YwclN5OFFLQmdRRHZLdE5uWkZOSDdFT3JXTGdvXG5yNUdmcVpETk1Cc1RlSVI2QWFvRENmVXFMaEFlSW9BZnczTHh2SG0vcmRpMkZsS2laMXJuanBHS29IcWZSNFIxXG5pM0pVanplaUxLaERUN2U4a054Q2lmZkdFWnBPR1RDcEJsUjhibGdyS3N2M29BRzFZTUlSbVpqSGRrZ1FGcTJkXG5GcGo5Vm1pc3hETEJEOVBJaWxUZUFSRGl0UUtCZ1FDNlVySzB0UnBJWHdTODZVbEdZZEFaRFl0QVNNck9adHhhXG5hRUZ2M25UdkVPeFROSTJGdlZuSzNHMEgyZU90bExTR3RWRHUzQVlaSk55ZXNZUWlPbUhMS09LSzB5SnB5ME1xXG5mUWoyTndFMzlTMVNYZHBXWHY0Zm1GbVQ4SXMvKzBPTnhZc1QvOFIvbmt3NDVGOXNxWllCMmpMbDcrL3pYS2wyXG5BQ2NMbmFURWpRS0JnRG9QcFg3R0prbWhtOVB2RjlZWXVUdVBpSzJuYmd0T0NLc3QyRDRnbnJuOHNNRUFFeWFpXG41amExVU1FdHpSeDNVdHhHUnhWTDBSMWNWQ2h5emo5UytSQjZMRUZjb2dTbFI2K3BZeTlzR3hDa21WYzRXazNPXG5VWmhibVYveFpjN1pzMUI3Q3VJRzdjWU9ldlFjN1V6amZZU1RBNXBkand5N2NPaVFYSVlBc0Q2NUFvR0JBSWIvXG5mRE9xTkF6VHE1OGtkODdpOTkvdkRFSGJlL1hvV1NlMytoR1A0TEdHVlhSRDAzWmZKenZ3VVo4cW8rZ1VvbWduXG4zeWZ4aXdtVXg3VERjYlZMRDZnZlMyVENiV0N4d1V4N280NmhjK1NUWSs4VnlTaGpVMFNaSWU0cWp2b2dsMldWXG5CNXZKNlJsK0hFUHNVNmRyaUNCM2RBRmR3MEZVbGdQRlFJVU9CMS9SQW9HQUlYdXlHVHB0UGNEdEFkMGFRR1k2XG5lMWhmbk05aGlSZEk2ZW1kN09yQU9WUy9xQnNKS25YS055N0IrcW5ueHY2c1p3eGNOL2FRMnh5TG5TVmp5MGxuXG5uTGxUcWw2K2orYSsrNEozMVZRWFBpdlN6Z3hNWld1RFZKenF4bEFhd1dpb0xDMklNVU5CNlQ2RHJXMGtUWnRvXG5VblVwWS9ZOTBHODN0TUI2VWdobnZwVT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsDQogICAgICAgICAgICAiY2xpZW50X2VtYWlsIjogImdjbG91ZC1idWNrZXQtYWNjZXNzQG15Zmlyc3RhcHAtNzIyNDAuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLA0KICAgICAgICAgICAgImNsaWVudF9pZCI6ICIxMDY4OTY4ODQyNDY4Mzg2Mjk4NDQiLA0KICAgICAgICAgICAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwNCiAgICAgICAgICAgICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLA0KICAgICAgICAgICAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLA0KICAgICAgICAgICAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZ2Nsb3VkLWJ1Y2tldC1hY2Nlc3MlNDBteWZpcnN0YXBwLTcyMjQwLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwNCiAgICAgICAgICAgICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iDQogICAgICAgICAgfSwNCiAgICAgICAgImVtYWlsIjogInJ1c2lydWhmZG9AZ21haWwuY29tIg0KICAgICAgfQ0KICAgIH0NCiAgfQ0KICA=


---



apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: backend
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==

---


apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: backend
data:
  DB_HOST: "104.155.137.239"
  DB_NAME: "myappdb"
  DB_USER: "myuser"

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: ica4-backend-deployment
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ica4-backend
  template:
    metadata:
      labels:
        app: ica4-backend
    spec:
      containers:
        - name: ica4-backend
          image: gcr.io/myfirstapp-72240/ica4-backend:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-configmap
            - secretRef:
                name: backend-secrets
      imagePullSecrets:
        - name: gcr-json-key


---

apiVersion: v1
kind: Service
metadata:
  name: ica4-backend-service
  namespace: backend
spec:
  type: LoadBalancer
  selector:
    app: ica4-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
